# Generated by Django 6.0.4 on 2026-05-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrierservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
