# Generated by Django 6.0.4 on 2026-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrierservice', '0003_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agent_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
