# Generated by Django 6.0.4 on 2026-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrierservice', '0004_package_agent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='events_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
