# Generated by Django 6.0.4 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrierservice', '0005_package_events_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='coordinates_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
